project_id = "tbdooscfrrkwfutkdjha"

[functions.create-admin-user]
verify_jwt = false

[functions.google-drive-import]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.notificar-encontros]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
